# syntax=docker/dockerfile:1.7

# ---- Stage 1: builder ----
# Installs full dep tree, runs `medusa build` (compiles TS + bundles admin
# dashboard via Vite). Output: apps/backend/.medusa/server — a self-contained
# Node app per Medusa v2's documented production-deploy pattern.
FROM node:20-bookworm-slim AS builder

# Native module build tools (some Medusa deps need them)
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 make g++ \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy workspace manifests first for layer caching
COPY package.json package-lock.json turbo.json .npmrc ./
COPY apps/backend/package.json ./apps/backend/

# Install full dep tree (dev deps required for medusa build)
RUN npm ci

# Copy source
COPY apps/backend ./apps/backend

# Build: produces apps/backend/.medusa/server with the bundled server + admin
RUN cd apps/backend && npm run build

# Install production-only deps inside the .medusa/server bundle.
# This is what Medusa v2 docs prescribe for production deploys.
# --legacy-peer-deps: Medusa v2.14.2 has an internal React 18/19 peer-dep
# conflict between @medusajs/icons (wants 19) and the rest of the bundle (18).
# Known harmless quirk; without this flag npm refuses to install.
RUN cd apps/backend/.medusa/server && npm install --omit=dev --legacy-peer-deps

# ---- Stage 2: runner ----
# Minimal image: only the .medusa/server bundle. The full source tree and
# dev-only deps from stage 1 are dropped.
FROM node:20-bookworm-slim AS runner

# Explicit NODE_ENV so the medusa-config.ts production boot guard (missing
# JWT_SECRET / COOKIE_SECRET must throw) never depends on the medusa CLI's
# undocumented `start` default.
ENV NODE_ENV=production

# ---- Railway cost control: cap the V8 old-space heap ----------------------
# Railway bills memory on ACTUAL resident bytes per minute ($10/GB-month), so
# on an idle service RAM is ~95% of the usage bill. Node does not know it is
# in a billed container: V8 sizes its default old-space from the HOST's total
# memory, sees gigabytes of headroom, and therefore defers major GC and lets
# collectable garbage pile up as resident — billed — bytes.
#
# 384 MB is a deliberate ceiling above the observed steady-state working set
# (~343 MB resident across the whole environment on the Aug 9-Sep 9 invoice),
# so V8 starts collecting instead of growing. It is NOT a hard RSS limit:
# resident = heap + native + code, so expect RSS above this number.
#
# If the service starts OOM-restarting (Railway shows SIGKILL / exit 137, and
# a crash loop costs far more than the RAM it saves), raise this to 512 by
# setting NODE_OPTIONS on the Railway service - that env var overrides this
# line without a rebuild.
ENV NODE_OPTIONS="--max-old-space-size=384"

# Run the HTTP server and the scheduled-job/workflow worker in ONE process.
# Medusa's alternative is a `server` + `worker` split, which on Railway means
# a second always-on container and therefore roughly DOUBLE the memory bill.
# At current volume (0.45% average CPU) one process is far from saturated, so
# the split would buy nothing. Set explicitly rather than relying on the
# default, so a future Medusa version change cannot silently double the bill.
ENV MEDUSA_WORKER_MODE=shared

WORKDIR /app

# Copy the self-contained server bundle (includes its own node_modules and
# the bundled admin dashboard at public/admin/)
COPY --from=builder /app/apps/backend/.medusa/server ./

# Medusa default port
EXPOSE 9000

# Run pending DB migrations on every container start (idempotent), then start
# the server. The medusa CLI is in node_modules/.bin from the production install.
#
# Two deliberate details here:
#
# 1. `./node_modules/.bin/medusa` instead of `npx medusa` for the migration.
#    npx resolves the local bin first, but if resolution ever misses (a partial
#    install, a hoisting change) it silently falls back to FETCHING the package
#    from the npm registry at container start - turning a boot into a network
#    download on every restart. The direct path fails loudly instead.
#
# 2. `exec` before the server. Without it the `sh` stays alive as PID 1 for the
#    life of the container, holding its own resident pages and swallowing
#    SIGTERM, so Railway's graceful stop degrades into a kill. `exec` replaces
#    the shell with the server process. `npm run start` is kept (rather than
#    calling the medusa binary directly) because the bundle's package.json is
#    GENERATED by `medusa build` - running its script is the contract Medusa
#    documents, and it survives the script changing between versions.
CMD ["sh", "-c", "./node_modules/.bin/medusa db:migrate && exec npm run start"]
